<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.2.2 (Python 3.8.6 on win32)" generated="20210127 17:54:44.431" rpa="false">
<suite id="s1" name="POCBD" source="C:\Users\Lucas Dias\Documents\Projetos\Nova pasta\POCBD.robot">
<test id="s1-t1" name="Banco de dados">
<kw name="Get Movie">
<arguments>
<arg>No One You Know</arg>
<arg>Somewhat Famous</arg>
</arguments>
<msg timestamp="20210127 17:54:44.658" level="TRACE">Arguments: [ ${artist}='No One You Know' | ${title}='Somewhat Famous' ]</msg>
<kw name="get">
<arguments>
<arg>${artist}</arg>
<arg>${title}</arg>
</arguments>
<msg timestamp="20210127 17:54:44.661" level="FAIL">No keyword with name 'get' found. Did you mean:
    BuiltIn.Get Time
    SeleniumLibrary.Get Text
    String.Get Line
    OperatingSystem.Get File</msg>
<status status="FAIL" starttime="20210127 17:54:44.661" endtime="20210127 17:54:44.661"></status>
</kw>
<status status="FAIL" starttime="20210127 17:54:44.657" endtime="20210127 17:54:44.661"></status>
</kw>
<status status="FAIL" starttime="20210127 17:54:44.657" endtime="20210127 17:54:44.662" critical="yes">No keyword with name 'get' found. Did you mean:
    BuiltIn.Get Time
    SeleniumLibrary.Get Text
    String.Get Line
    OperatingSystem.Get File</status>
</test>
<status status="FAIL" starttime="20210127 17:54:44.434" endtime="20210127 17:54:44.664"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1">Critical Tests</stat>
<stat pass="0" fail="1">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" id="s1" name="POCBD">POCBD</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20210127 17:54:44.655" level="ERROR">Error in file 'C:\Users\Lucas Dias\Documents\Projetos\Nova pasta\POCBD.robot' on line 8: Importing test library 'C:\Users\Lucas Dias\Documents\Projetos\Nova pasta\biblioteca.py' failed: SyntaxError: invalid syntax (biblioteca.py, line 40)
Traceback (most recent call last):
  None
PYTHONPATH:
  C:\Users\Lucas Dias\.virtualenvs\Nova_pasta-QANRwr3B\Scripts\robot.exe
  c:\users\lucas dias\documents\softwares\python38.zip
  c:\users\lucas dias\documents\softwares\DLLs
  c:\users\lucas dias\documents\softwares\lib
  c:\users\lucas dias\documents\softwares
  c:\users\lucas dias\.virtualenvs\nova_pasta-qanrwr3b
  c:\users\lucas dias\.virtualenvs\nova_pasta-qanrwr3b\lib\site-packages</msg>
</errors>
</robot>
